### ISSUE TITLE
updates failing.

### ISSUE THREAD

**Issue by guruward** [algolia/mongo-connector#10]
ERROR:mongo_connector.util:Fatal Exception
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/stephenward/mongo-connector/env/lib/python2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/util.py", line 85, in wrapped
    func(_args, *_kwargs)
  File "/Users/stephenward/mongo-connector/env/lib/python2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/oplog_manager.py", line 264, in run
    ns, timestamp)
  File "/Users/stephenward/mongo-connector/env/lib/python2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/doc_managers/algolia_doc_manager.py", line 255, in update
    self.upsert(self.apply_update(doc, update_spec), True)
  File "/Users/stephenward/mongo-connector/env/lib/python2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/doc_managers/algolia_doc_manager.py", line 261, in upsert
    self.last_object_id = serialize(doc[self.unique_key])
KeyError: '_id'

**Comment by Nagriar** [comment]
Thanks @guruward
