### ISSUE TITLE
app crashes when trying to remap

### ISSUE THREAD

**Issue by guruward** [algolia/mongo-connector#11]
Logging to mongo-connector.log.
Traceback (most recent call last):
  File "/Users/stephenward/mongo-connector/env/lib/python2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/oplog_manager.py", line 490, in do_dump
    upsert_all(dm)
  File "/Users/stephenward/mongo-connector/env/lib/python2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/oplog_manager.py", line 474, in upsert_all
    dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
  File "/Users/stephenward/mongo-connector/env/lib/python2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/doc_managers/doc_manager_base.py", line 99, in bulk_upsert
    self.upsert(doc, namespace, timestamp)
  File "/Users/stephenward/mongo-connector/env/lib/python2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/doc_managers/algolia_doc_manager.py", line 263, in upsert
    self.attributes_filter)
  File "/Users/stephenward/mongo-connector/env/lib/python2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/doc_managers/algolia_doc_manager.py", line 237, in apply_filter
    elif filter_value(value, filter[raw_key]):
  File "/Users/stephenward/mongo-connector/env/lib/python2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/doc_managers/algolia_doc_manager.py", line 118, in filter_value
    """.format(**locals()))
KeyError: 'filter'
ERROR:mongo_connector.oplog_manager:OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient(xxxxxxxxxxxx)
ERROR:mongo_connector.connector:MongoConnector: OplogThread <OplogThread(Thread-3, started 4473491456)> unexpectedly stopped! Shutting down

**Comment by Nagriar** [comment]
Thanks for the feedback @guruward
