### ISSUE TITLE
SSL errors when updating

### ISSUE THREAD

**Issue by benjamine** [algolia/mongo-connector#16]
Hi guys, yesterday (around 12:10pm ET) our connector updates started to fail with these `'SSL routines', 'SSL3_WRITE_PENDING', 'bad write retry'` (see full log below)

we're not sure if there were a change in ssl certs for example, but I'm not sure if we might need to update something in the connector dependencies (like openssl).

```
2015-10-07T08:31:59.111488+00:00 app[worker.1]: DEBUG:mongo_connector.oplog_manager:OplogThread: Operation for this entry is u
2015-10-07T08:31:59.212880+00:00 app[worker.1]: ERROR:mongo_connector.util:Fatal Exception
2015-10-07T08:31:59.454458+00:00 app[worker.1]: Exception in thread Thread-3:
2015-10-07T08:31:59.454463+00:00 app[worker.1]: Traceback (most recent call last):
2015-10-07T08:31:59.454465+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-10-07T08:31:59.454467+00:00 app[worker.1]:     self.run()
2015-10-07T08:31:59.454469+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/util.py", line 85, in wrapped
2015-10-07T08:31:59.454470+00:00 app[worker.1]:     func(*args, **kwargs)
2015-10-07T08:31:59.454472+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/oplog_manager.py", line 264, in run
2015-10-07T08:31:59.454473+00:00 app[worker.1]:     ns, timestamp)
2015-10-07T08:31:59.454476+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/doc_managers/algolia_doc_manager.py", line 343, in update
2015-10-07T08:31:59.454478+00:00 app[worker.1]:     self.upsert(doc, False, namespace, timestamp)
2015-10-07T08:31:59.454480+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/doc_managers/algolia_doc_manager.py", line 369, in upsert
2015-10-07T08:31:59.454481+00:00 app[worker.1]:     self.commit()
2015-10-07T08:31:59.454483+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/doc_managers/algolia_doc_manager.py", line 403, in commit
2015-10-07T08:31:59.454484+00:00 app[worker.1]:     self.index.batch({'requests': self.batch})
2015-10-07T08:31:59.454486+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/algoliasearch-1.6.7-py2.7.egg/algoliasearch/index.py", line 805, in batch
2015-10-07T08:31:59.454487+00:00 app[worker.1]:     body=requests)
2015-10-07T08:31:59.454488+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/algoliasearch-1.6.7-py2.7.egg/algoliasearch/index.py", line 812, in _perform_request
2015-10-07T08:31:59.454490+00:00 app[worker.1]:     params=params, body=body, is_search=is_search)
2015-10-07T08:31:59.454491+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/algoliasearch-1.6.7-py2.7.egg/algoliasearch/client.py", line 500, in _perform_request
2015-10-07T08:31:59.454493+00:00 app[worker.1]:     params=params, data=body, timeout=timeout)
2015-10-07T08:31:59.454495+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/requests-2.8.0-py2.7.egg/requests/sessions.py", line 471, in request
2015-10-07T08:31:59.454497+00:00 app[worker.1]:     resp = self.send(prep, **send_kwargs)
2015-10-07T08:31:59.454501+00:00 app[worker.1]:     r = adapter.send(request, **kwargs)
2015-10-07T08:31:59.454499+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/requests-2.8.0-py2.7.egg/requests/sessions.py", line 579, in send
2015-10-07T08:31:59.454503+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/requests-2.8.0-py2.7.egg/requests/adapters.py", line 369, in send
2015-10-07T08:31:59.454505+00:00 app[worker.1]:     timeout=timeout
2015-10-07T08:31:59.454511+00:00 app[worker.1]:     body=body, headers=headers)
2015-10-07T08:31:59.454509+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/requests-2.8.0-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
2015-10-07T08:31:59.454513+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/requests-2.8.0-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
2015-10-07T08:31:59.454515+00:00 app[worker.1]:     conn.request(method, url, **httplib_request_kw)
2015-10-07T08:31:59.454517+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/httplib.py", line 1053, in request
2015-10-07T08:31:59.454519+00:00 app[worker.1]:     self._send_request(method, url, body, headers)
2015-10-07T08:31:59.454521+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/httplib.py", line 1093, in _send_request
2015-10-07T08:31:59.454523+00:00 app[worker.1]:     self.endheaders(body)
2015-10-07T08:31:59.454525+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/httplib.py", line 1049, in endheaders
2015-10-07T08:31:59.454526+00:00 app[worker.1]:     self._send_output(message_body)
2015-10-07T08:31:59.454528+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/httplib.py", line 893, in _send_output
2015-10-07T08:31:59.454530+00:00 app[worker.1]:     self.send(msg)
2015-10-07T08:31:59.454532+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/httplib.py", line 869, in send
2015-10-07T08:31:59.454534+00:00 app[worker.1]:     self.sock.sendall(data)
2015-10-07T08:31:59.454536+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/requests-2.8.0-py2.7.egg/requests/packages/urllib3/contrib/pyopenssl.py", line 220, in sendall
2015-10-07T08:31:59.454537+00:00 app[worker.1]:     sent = self._send_until_done(data[total_sent:total_sent+SSL_WRITE_BLOCKSIZE])
2015-10-07T08:31:59.454541+00:00 app[worker.1]:     return self.connection.send(data)
2015-10-07T08:31:59.454539+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/requests-2.8.0-py2.7.egg/requests/packages/urllib3/contrib/pyopenssl.py", line 206, in _send_until_done
2015-10-07T08:31:59.454542+00:00 app[worker.1]:   File "build/bdist.linux-x86_64/egg/OpenSSL/SSL.py", line 1271, in send
2015-10-07T08:31:59.454544+00:00 app[worker.1]:     self._raise_ssl_error(self._ssl, result)
2015-10-07T08:31:59.454546+00:00 app[worker.1]:   File "build/bdist.linux-x86_64/egg/OpenSSL/SSL.py", line 1187, in _raise_ssl_error
2015-10-07T08:31:59.454548+00:00 app[worker.1]:     _raise_current_error()
2015-10-07T08:31:59.454550+00:00 app[worker.1]:   File "build/bdist.linux-x86_64/egg/OpenSSL/_util.py", line 48, in exception_from_error_queue
2015-10-07T08:31:59.454552+00:00 app[worker.1]:     raise exception_type(errors)
2015-10-07T08:31:59.454553+00:00 app[worker.1]: Error: [('SSL routines', 'SSL3_WRITE_PENDING', 'bad write retry')]
2015-10-07T08:31:59.454555+00:00 app[worker.1]:
2015-10-07T08:32:03.027083+00:00 app[worker.1]: INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2201): RA8BA33XSG.algolia.net
2015-10-07T08:32:03.060380+00:00 app[worker.1]: WARNING:root:[('SSL routines', 'SSL3_WRITE_PENDING', 'bad write retry')]
2015-10-07T08:32:13.119099+00:00 app[worker.1]: INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2202): RA8BA33XSG.algolia.net
2015-10-07T08:32:13.146284+00:00 app[worker.1]: WARNING:root:[('SSL routines', 'SSL3_WRITE_PENDING', 'bad write retry')]
2015-10-07T08:32:23.201990+00:00 app[worker.1]: INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2203): RA8BA33XSG.algolia.net
2015-10-07T08:32:23.226980+00:00 app[worker.1]: WARNING:root:[('SSL routines', 'SSL3_WRITE_PENDING', 'bad write retry')]
2015-10-07T08:32:33.286569+00:00 app[worker.1]: INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2204): RA8BA33XSG.algolia.net
2015-10-07T08:32:33.349392+00:00 app[worker.1]: WARNING:root:[('SSL routines', 'SSL3_WRITE_PENDING', 'bad write retry')]
2015-10-07T08:32:43.415631+00:00 app[worker.1]: INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2205): RA8BA33XSG.algolia.net
2015-10-07T08:32:45.466641+00:00 app[worker.1]: WARNING:root:[('SSL routines', 'SSL3_WRITE_PENDING', 'bad write retry')]
2015-10-07T08:32:55.521727+00:00 app[worker.1]: INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2206): RA8BA33XSG.algolia.net
2015-10-07T08:32:55.579864+00:00 app[worker.1]: WARNING:root:[('SSL routines', 'SSL3_WRITE_PENDING', 'bad write retry')]
2015-10-07T08:33:05.646828+00:00 app[worker.1]: INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2207): RA8BA33XSG.algolia.net
2015-10-07T08:33:05.674921+00:00 app[worker.1]: WARNING:root:[('SSL routines', 'SSL3_WRITE_PENDING', 'bad write retry')]
2015-10-07T08:33:15.732566+00:00 app[worker.1]: INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2208): RA8BA33XSG.algolia.net
2015-10-07T08:33:15.816747+00:00 app[worker.1]: WARNING:root:[('SSL routines', 'SSL3_WRITE_PENDING', 'bad write retry')]
2015-10-07T08:33:25.936284+00:00 app[worker.1]: INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2209): RA8BA33XSG.algolia.net
2015-10-07T08:33:26.023600+00:00 app[worker.1]: WARNING:root:[('SSL routines', 'SSL3_WRITE_PENDING', 'bad write retry')]
2015-10-07T08:33:36.088213+00:00 app[worker.1]: INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2210): RA8BA33XSG.algolia.net
2015-10-07T08:33:36.143589+00:00 app[worker.1]: WARNING:root:[('SSL routines', 'SSL3_WRITE_PENDING', 'bad write retry')]
2015-10-07T08:33:46.227000+00:00 app[worker.1]: INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2211): RA8BA33XSG.algolia.net
2015-10-07T08:33:46.254092+00:00 app[worker.1]: WARNING:root:[('SSL routines', 'SSL3_WRITE_PENDING', 'bad write retry')]
2015-10-07T08:33:56.779969+00:00 app[worker.1]: INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2212): RA8BA33XSG.algolia.net
2015-10-07T08:33:57.238558+00:00 app[worker.1]: WARNING:root:[('SSL routines', 'SSL3_WRITE_PENDING', 'bad write retry')]
2015-10-07T08:34:07.303371+00:00 app[worker.1]: INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2213): RA8BA33XSG.algolia.net
2015-10-07T08:34:07.325317+00:00 app[worker.1]: WARNING:root:[('SSL routines', 'SSL3_WRITE_PENDING', 'bad write retry')]
2015-10-07T08:34:17.388970+00:00 app[worker.1]: INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2214): RA8BA33XSG.algolia.net
2015-10-07T08:34:17.418664+00:00 app[worker.1]: WARNING:root:[('SSL routines', 'SSL3_WRITE_PENDING', 'bad write retry')]
2015-10-07T08:34:27.474467+00:00 app[worker.1]: INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2215): RA8BA33XSG.algolia.net
2015-10-07T08:34:27.611614+00:00 app[worker.1]: WARNING:root:[('SSL routines', 'SSL3_WRITE_PENDING', 'bad write retry')]
2015-10-07T08:34:37.695027+00:00 app[worker.1]: INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2216): RA8BA33XSG.algolia.net
2015-10-07T08:34:37.828600+00:00 app[worker.1]: WARNING:root:[('SSL routines', 'SSL3_WRITE_PENDING', 'bad write retry')]
2015-10-07T08:34:47.884248+00:00 app[worker.1]: INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2217): RA8BA33XSG.algolia.net
2015-10-07T08:34:47.905449+00:00 app[worker.1]: WARNING:root:[('SSL routines', 'SSL3_WRITE_PENDING', 'bad write retry')]
2015-10-07T08:34:57.966421+00:00 app[worker.1]: INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2218): RA8BA33XSG.algolia.net
```

we run the connector in a heroku instance, some version numbers:
- python 2.7
- algoliasearch 1.6.7
- pyOpenSSL 0.15.1
- cryptography 1.0.2

**Comment by benjamine** [comment]
we solved it by adding this to our requirements.txt:

```
requests[security]==2.7.0
```

(last version 2.8.0 is causing the problem)

**Comment by redox** [comment]
:+1: @benjamine, crazy python /o\
