### ISSUE TITLE
Question : Limit Fields

### ISSUE THREAD

**Issue by patrickml** [algolia/mongo-connector#19]
How can you limit the oplog trailing to only work for specific fields. IE I have a large document but I only want 3 of the fields sent to Algolia

**Comment by Nagriar** [comment]
You can use the post processing script in python to do easily:
In a file algolia_postproc_INDEXNAME.py, you can put this script:

_$ = { "attr1":  _$["attr1"], "attr2":  _$["attr2"], "attr3":  _$["attr3"]}

where _$ is the document from your mongo collection.

**Comment by patrickml** [comment]
@Nagriar thanks for the reply. I just tried to do that and i am getting this error. Any ideas?

``` txt
ERROR:mongo_connector.util:Fatal Exception
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/oplog_manager.py", line 264, in run
    ns, timestamp)
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/doc_managers/algolia_doc_manager.py", line 261, in update
    self.upsert(self.apply_update(doc, update_spec), True)
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/doc_managers/algolia_doc_manager.py", line 278, in upsert
    exec(re.sub(r"_\$", "filtered_doc", self.postproc))
  File "<string>", line 1, in <module>
KeyError: 'address'

```

This is my code

``` py
_$ = { "_id": _$["_id"], "address": _$["address"], "name": _$["name"],  "account": _$["account"] }
```

**Comment by patrickml** [comment]
I fixed the python issue i was having but now im having an issue on Algolia. I am now seeing this in the logs

``` txt
{
  "message": "The 'objectID' attribute is required to use action=partialUpdateObject near line:1 column:127",
  "status": 400
}
```

**Comment by patrickml** [comment]
I was able to get the result i wanted by using `algolia_fields_branches.json`

``` json
{
    "_id" : "",
    "address" : "",
    "name" : "",
    "account" : ""
}
```

**Comment by Nagriar** [comment]
Ah yes sorry, I forgot to copy the objectID in my example that's why it didn't work. Cool!

**Comment by patrickml** [comment]
Any idea why i might be getting this error?

``` txt
ERROR:mongo_connector.util:Fatal Exception
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/oplog_manager.py", line 264, in run
    ns, timestamp)
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/doc_managers/algolia_doc_manager.py", line 261, in update
    self.upsert(self.apply_update(doc, update_spec), True)
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/doc_managers/algolia_doc_manager.py", line 246, in apply_update
    doc = super(DocManager, self).apply_update(doc, update_spec)
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/doc_managers/doc_manager_base.py", line 70, in apply_update
    wl = len(where)
TypeError: object of type 'NoneType' has no len()
```
