### ISSUE TITLE
ObjectID does not exist

### ISSUE THREAD

**Issue by redox** [algolia/mongo-connector#4]
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "build/bdist.linux-x86_64/egg/mongo_connector/oplog_manager.py", line 141, in run
    cursor, cursor_len = self.init_cursor()
  File "build/bdist.linux-x86_64/egg/mongo_connector/oplog_manager.py", line 564, in init_cursor
    self.checkpoint = self.rollback()
  File "build/bdist.linux-x86_64/egg/mongo_connector/oplog_manager.py", line 631, in rollback
    last_docs.append(dm.get_last_doc())
  File "./doc_managers/algolia_doc_manager.py", line 329, in get_last_doc
    "Could not connect to Algolia Search: %s" % e)
ConnectionFailed: Could not connect to Algolia Search: u'ObjectID does not exist'
```

**Comment by benjamine** [comment]
Hi, I found the same error, gets fixed with #8

**Comment by guruward** [comment]
ERROR:mongo_connector.util:Fatal Exception
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/stephenward/mongo-connector/env/lib/python2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/util.py", line 85, in wrapped
    func(_args, *_kwargs)
  File "/Users/stephenward/mongo-connector/env/lib/python2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/oplog_manager.py", line 264, in run
    ns, timestamp)
  File "/Users/stephenward/mongo-connector/env/lib/python2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/doc_managers/algolia_doc_manager.py", line 254, in update
    doc = self.index.getObject(str(document_id))
  File "/Users/stephenward/mongo-connector/env/lib/python2.7/site-packages/algoliasearch-1.5.4-py2.7.egg/algoliasearch/algoliasearch.py", line 54, in newFunc
    return func(_args, *_kwargs)
  File "/Users/stephenward/mongo-connector/env/lib/python2.7/site-packages/algoliasearch-1.5.4-py2.7.egg/algoliasearch/algoliasearch.py", line 456, in getObject
    return self.get_object(object_id, attributes_to_retrieve)
  File "/Users/stephenward/mongo-connector/env/lib/python2.7/site-packages/algoliasearch-1.5.4-py2.7.egg/algoliasearch/algoliasearch.py", line 466, in get_object
    return AlgoliaUtils_request(self.client.headers, self.read_hosts, "GET", "/1/indexes/%s/%s" % (self.url_index_name, obj_id), self.client.timeout)
  File "/Users/stephenward/mongo-connector/env/lib/python2.7/site-packages/algoliasearch-1.5.4-py2.7.egg/algoliasearch/algoliasearch.py", line 988, in AlgoliaUtils_request
    raise e
AlgoliaException: u'ObjectID does not exist'
